const SOURCES=[{title:'Nederlands Jeugdinstituut — Opvoeden en ouderschap',url:'https://www.nji.nl/kennis/opvoeden-ouderschap/wat-is-opvoeden',reason:'Algemene achtergrond over opvoeden en de ouder-kindrelatie.'},{title:'Nederlands Jeugdinstituut — Pubers',url:'https://www.nji.nl/kennis/ontwikkeling/puber-algemene-ontwikkeling',reason:'Achtergrond over ontwikkeling en gedrag tijdens de puberteit.'}];
const MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
function out(res,n,x){res.status(n).json(x)}
function text(d){if(d.output_text)return d.output_text;return (d.output||[]).flatMap(i=>i.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join('\n')}
async function ai(instructions,input,useWeb=false){if(!process.env.OPENAI_API_KEY)throw Error('OPENAI_API_KEY ontbreekt op de hosting.');const body={model:MODEL,instructions,input};if(useWeb){body.tools=[{type:'web_search',search_context_size:'medium',user_location:{type:'approximate',city:'Emmen',country:'NL',region:'Drenthe',timezone:'Europe/Amsterdam'}}];body.tool_choice='auto'}const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||'OpenAI API-fout.');return text(d)}
function parse(x){try{return JSON.parse(x)}catch{const m=x.match(/\{[\s\S]*\}/);if(m)return JSON.parse(m[0]);throw Error('Ongeldige AI-uitvoer.')}}
export default async function handler(req,res){
if(req.method!=='POST')return out(res,405,{error:'Gebruik POST.'});
try{const b=req.body||{};
if(b.action==='analyze'){const story=String(b.story||'').trim();if(story.length<8)return out(res,400,{error:'Vertel iets meer over de situatie.'});const p='Je bent OuderHulp. Analyseer eerst de oudervraag, zonder advies of diagnose. Vat eerlijk samen. Antwoord alleen JSON met core_question, parent_goal, topic, age en unknowns.';const a=parse(await ai(p,story));return out(res,200,{analysis:{core_question:String(a.core_question||''),parent_goal:String(a.parent_goal||''),topic:String(a.topic||''),age:a.age?String(a.age):null,unknowns:Array.isArray(a.unknowns)?a.unknowns.map(String).slice(0,6):[]}})}
if(b.action==='answer'){const prompt='Je bent OuderHulp, een empathische Nederlandse oudercoach. Geef rustig, praktisch en niet-veroordelend advies. Stel geen diagnose. Geef concrete stappen, een voorbeeldzin en maximaal één vervolgvraag. Bij direct gevaar: adviseer 112. Je hebt toegang tot actuele webzoekfunctie. Zoek voor dit antwoord actief op internet naar relevante en betrouwbare bronnen. Geef voor actuele of veranderlijke informatie altijd de gevonden bronnen. Geef bij voorkeur Nederlandse, officiële of deskundige bronnen (zoals overheid, NJi, VeiligheidNL, Thuisarts of vergelijkbare professionele organisaties), maar gebruik andere betrouwbare bronnen als dat nodig is. Baseer het advies op de gevonden informatie en maak duidelijk wanneer informatie algemeen is. Antwoord alleen JSON met answer_html, followup en sources. answer_html mag alleen veilige tags p,h3,ol,ul,strong,blockquote bevatten en geen links, script of style. sources moet een array zijn met maximaal 6 objecten met title, url en reason. Gebruik echte URL\'s uit de webzoekresultaten en verzin geen bronnen.';const input='Verhaal:\n'+String(b.story||'')+'\nBegrip:\n'+JSON.stringify(b.analysis||{})+'\nGesprek:\n'+JSON.stringify(b.conversation||[]);const r=parse(await ai(prompt,input,true));r.sources=Array.isArray(r.sources)?r.sources.slice(0,6).filter(s=>s&&s.url).map(s=>({title:String(s.title||s.url),url:String(s.url),reason:String(s.reason||'Relevante bron voor dit advies.')})):[];r.followup=r.followup?String(r.followup):null;r.answer_html=String(r.answer_html||'').replace(/<script[\\s\\S]*?<\\/script>/gi,'');return out(res,200,r)}
return out(res,400,{error:'Onbekende actie.'})}catch(e){console.error(e);return out(res,500,{error:e.message||'Er ging iets mis.'})}}